server:
  port: ${PORT:0}

eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}


spring:
  application.name: user-ws
  devtools.restart.enabled: true
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true
    settings.web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

api-gateway.ip: 169.254.58.236

token:
  expiration: 864000000
  secret: j3F##@F$@@FSFEGRETE
app:
  config:
    security-url: users/login