server.port: 8088
spring.application.name: users-ws

eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}


spring.devtools.restart.enabled: true
spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true


spring.h2.console:
    enabled: true
    settings.web-allow-others: true

#H2 database
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

#Mysql: this config move to config server
#spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#spring.datasource:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
#  username: user
#  password: root


api-gateway.ip: 169.254.58.236
token:
  expiration: 864000000
  secret: j3F##@F$@@FSFEGRETE


app.config:
    security-url: users/login


sping.config:
  import: "optional:configserver:http://localhost:8012"


spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest