spring.application.name: account-manager-ws
server.port: ${PORT:0}

spring:
  devtool.restart.enabled: true

eureka:
  client.service.defaultZone: http://localhost:8010/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}


spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest