server:
  port: 0
spring:
  application:
    name: account-manager-ws
  devtool:
    restart:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    service:
      defaultZone: http://localhost:8010/eureka
